export const reasons = [
  'I love the way you say "no" when you\'re pretending to be annoyed.',
  "I love how your nose scrunches when you laugh.",
  "I love how you glow when you smile.",
  "I love that you try to understand my world.",
  "I love the way you you sleep in neck cranny.",
  "I love how you text me first sometimes.",
  "I love that everytime I'm with you it feels like home.",
  "I love that you are addicted to variyari.",
  "I love that you call me smol.",
  "I love how you always steal the blanket.",
  "I love that you randomly go quiet when you're thinking deeply.",
  "I love how you get fake mad when I tease you but you secretly like it.",
  "I love the way you hold my bicep.",
  "I love that you remember small details about my day that I don't remember.",
  "I love how you look at me when you're proud of me.",
  "I love the specific smile you have when you're trying not to smile.",
  "I love how you tuck your hair behind your ear when you're focused.",
  'I love that you ask "did you eat?" like it\'s your full-time job.',
  "I love the way you say my name (when you do say it).",
  "I love how you melt into me when we sit on the couch together.",
  "I love your sleepy voice when we wake up.",
  "I love how dramatic you get over tiny inconveniences.",
  'I love that you send me reels and say "us" or "you" or "me"',
  "I love how you get protective over me.",
  "I love that you'll argue your point even if you're 5% unsure.",
  "I love how you look in my oversized hoodies.",
  "I love that you get excited about the most random things.",
  "I love your 'you're so dumb' face.",
  "I love that you trust me with your vulnerable thoughts.",
  'I love the way you say "come here."',
  "I love how your eyes soften when you're tired.",
  "I love that you hype me up even when I don't believe in myself.",
  "I love your stubbornness.",
  "I love how you walk slightly faster when you're excited.",
  "I love that you care deeply, even when it costs you energy.",
  "I love how safe you make me feel.",
  "I love that you can switch from cute to serious in 0.2 seconds.",
  "I love how you play with your rings/bracelet when you're nervous.",
  "I love that you make ordinary days feel important.",
  "I love your random late-night thoughts.",
  "I love how you check in on me without making it a big thing.",
  "I love that you try to understand me instead of just reacting.",
  "I love your competitive side.",
  "I love how you look at me across the room.",
  "I love that you pretend not to care but absolutely care.",
  "I love how you soften when I pull you closer.",
  "I love that you laugh at my bad jokes.",
  'I love how you say "shut up" when you\'re flustered.',
  "I love your little sighs.",
  "I love that you want to build a future, not just have moments.",
  "I love how you get shy after compliments.",
  "I love your loyalty.",
  "I love how you stand up for the people you love.",
  "I love that you challenge me.",
  "I love how you get quiet when you're overwhelmed and let me sit with you.",
  "I love your confidence when you walk into a room.",
  "I love how you care about how I'm really doing.",
  'I love that you\'ll send "reached home" without me asking.',
  'I love the way you say "hmm?"',
  "I love that you remember my favorite things.",
  "I love your soft side that only I see.",
  "I love how you adjust your voice when you're comforting me.",
  "I love that you let me see you without makeup and without guard.",
  "I love how you pretend to be strong but still let me hold you.",
  "I love that you get jealous in the cutest way.",
  "I love your little eye rolls.",
  "I love how you calm down when I hug you.",
  "I love that you care about your family so much.",
  "I love how you sit close even when there's space.",
  'I love the way you say "goodnight."',
  "I love that you share your dreams with me.",
  "I love how you get stubborn about your opinions.",
  "I love that you want me around.",
  "I love how you make me feel chosen.",
  "I love the way you look when you're lost in thought.",
  "I love that you don't give up on us.",
  "I love how you adjust your hair in mirrors.",
  "I love that you secretly love when I'm possessive in a healthy way.",
  "I love how you soften when I call you chakli.",
  "I love that you let me protect you but don't need me to.",
  "I love your random bursts of motivation.",
  "I love how you look when you're focused on your goals.",
  "I love that you try for us.",
  "I love your gentle heart.",
  "I love how you get sleepy and clingy.",
  "I love that you ask for reassurance instead of bottling it up.",
  "I love how you squeeze my hand when something overwhelms you.",
  "I love that you choose honesty even when it's hard.",
  "I love your warmth.",
  "I love that you trust me with your heart.",
  "I love how you listen.",
  "I love that you make space for my ambitions.",
  "I love your ambition.",
  "I love that you let me see your insecure moments.",
  "I love how you make me softer.",
  "I love that you push me to grow.",
  "I love how you forgive.",
  "I love that you're mine.",
  "I love that I get to love you.",
  "I love you because you're you, you're my chakli. And no one else could ever be.",
];
